before_install:
  - sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
  - wget https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-installer-linux-x86_64.sh
  - chmod +x bazel-0.19.2-installer-linux-x86_64.sh
  - ./bazel-0.19.2-installer-linux-x86_64.sh
before_script:
  - sudo sh install/install_prereqs_ubuntu.sh
script:
  - bazel build ...
